### ISSUE TITLE
Firefox下使用暴力猴需要更改格式,并使用未压缩的脚本才可以正常加载

### ISSUE THREAD

**Issue by KCCat** [andywang425/Bilibili-SGTH#11]
**描述bug**  
Firefox下使用暴力猴需要更改格式才可以正常加载. 
`Uncaught ReferenceError: BilibiliAPI is not defined` 
控制台如上提示.
将4条 `require` 语句从
 `//@require https://cdn.jsdelivr.net/gh/jquery/jquery@3.2.1/dist/jquery.min.js`
修改成
 `// @require https://cdn.jsdelivr.net/gh/jquery/jquery@3.2.1/dist/jquery.min.js`
可以加载.
点击 `立刻开始送礼` 会出现新的错误信息
`[IGIFTMSG] ReferenceError: assignment to undeclared variable ArrayEXCLUDE_ROOMID`
改用未压缩的脚本可以正常送礼.

**使用环境:**
 - 浏览器: Linux/Firefox/暴力猴v2.12.7
 - 浏览器版本: 78.0.2
 - 脚本的版本: 3.7.3
 - 网络情况(网速): 好

**Comment by andywang425** [comment]
谢谢反馈，我会在下个版本中修改require格式并改用一种安全性较高（但压缩率低）的压缩方法。

**Comment by andywang425** [comment]
greasyfork有个bug，如果require前加了空格就报错不能上传。。。所以只能这样了，如有不便还请谅解。

**Comment by andywang425** [comment]
> **描述bug**
> Firefox下使用暴力猴需要更改格式才可以正常加载.
> `Uncaught ReferenceError: BilibiliAPI is not defined`
> 控制台如上提示.
> 将4条 `require` 语句从
> `//@require https://cdn.jsdelivr.net/gh/jquery/jquery@3.2.1/dist/jquery.min.js`
> 修改成
> `// @require https://cdn.jsdelivr.net/gh/jquery/jquery@3.2.1/dist/jquery.min.js`
> 可以加载.
> 点击 `立刻开始送礼` 会出现新的错误信息
> `[IGIFTMSG] ReferenceError: assignment to undeclared variable ArrayEXCLUDE_ROOMID`
> 改用未压缩的脚本可以正常送礼.
> 
> **使用环境:**
> 
> * 浏览器: Linux/Firefox/暴力猴v2.12.7
> * 浏览器版本: 78.0.2
> * 脚本的版本: 3.7.3
> * 网络情况(网速): 好

我刚刚去看了下gf的库文件链接要求，原来我这几个链接是不符合规范的。而我无意中用一种特别的写法绕过了gf的require链接检查。。。
