### ISSUE TITLE
无法使用问题

### ISSUE THREAD

**Issue by xqltt** [andywang425/Bilibili-SGTH#2]
今天的脚本为何无法正常使用了?刷新直播间后无法加载脚本的界面,仅有三个提示
1.脚本配置载入成功
2.CACHE载入成功
3.Apptoken载入成功

**Comment by coolestsubio** [comment]
3.4就有这个问题了
3.3正常

**Comment by andywang425** [comment]
请按规定格式进行反馈。可以先试试v3.3的脚本，链接在README。
