### ISSUE TITLE
BUG反馈【自动投币】【礼物到期时间】

### ISSUE THREAD

**Issue by 15726238368** [andywang425/Bilibili-SGTH#7]
【自动投币】硬币不足时会陷入死循环，控制台一直提示硬币不足，页面浮动提示[自动每日奖励][每日投币]'undefined
【礼物到期时间】默认为86400(即1天)，但修改成其他数值后（比如172800(2天)、2592000(30天)）再手动点击立即送礼，依然只会送出剩余时间为1天的礼物，2天以上的不会送出。
怀疑是设置未应用，或者数值溢出。
个人建议修复bug的同时将礼物到期时间改为以天为单位，因为包裹中的辣条是每天过期一次的，不需要精确到秒

**Comment by andywang425** [comment]
好像是b站更新导致的。。。以后会把礼物到期时间改为以天为单位

**Comment by andywang425** [comment]
【自动投币】已修改，但我没有条件去测试。
【礼物到期时间】我测下来没这个bug。其实礼物的过期时间是精确到毫秒的（每种礼物的expire_at属性），我觉得有必要精确到秒。

**Comment by 15726238368** [comment]
想问一下关于“礼物过期时间是精确到毫秒的”，是指“剩余有效时长”精确到毫秒还是“过期时间点”精确到毫秒？
因为我在包裹中看到的有效期都是以天为单位，并且实测也都是统一在24:00过期(为方便 使用24:00代表次日00:00)，没见过哪个物品中午过期的。

我的理解是(基于实测)：
假设现在时间是23:59:00，包裹中显示“1天”的礼物，它的剩余时间应该是t=60s，过期时间是t0=24:00:00；
30s过后，当前时间时间来到23:59:30，则变为t=30s，而t0=24:00:00并不会变。

而按照你说的精确到毫秒的expire_at好像是对应于我上面的t0吗？也就是说并不是所有礼物都在某天的0点过期吗？如果程序是这样的，这与实际不符啊，实际就是所有礼物都会在0点过期啊(难道是有偷偷在中午过期的我没发现？)
如果过期时间点t0不都是在0点的话，包裹里的天数又是怎么计算的呢？显示1天的是指会在今天过期但可能不到24点就过期了吗？
————————————————————
而如果你说的expire_at是对应于我上面的t，也就是说这个数值会随着时间而减少，并在0点减小为0从而过期，那我觉得单位设置为天没有问题啊。就是把包裹中显示的天数小于等于设置天数的所有礼物都送出。(但我从变量命名来看应该不是这种情况)

总之就是，如果礼物都是在某天0点过期，那设置为天是没问题的。但是如果不是都在0点过期，那就超出我的认知范围了，可以忽略我的这些看法。
（我刚刚测试了23:59领了3个舰长辣条(1天)并且不送出，然后到0点时这3个辣条就从包裹里消失了；原来显示2天的辣条变为显示1天，但数量也没有增加，说明那3个确实过期了而不是合并到第二天的辣条里了。也就是说这3个辣条从从领取到过期只有几十秒。基于测试我还是认为礼物是在0点过期的。如果不是的话能告诉我一下领取的舰长辣条的过期时间/有效时间是多少吗？

**Comment by andywang425** [comment]
这么说的话可以改成天。我自己算了下发现所有礼物确实都在0点过期。

**Comment by 15726238368** [comment]
【自动投币】实测还是会死循环
![coin_log](https://user-images.githubusercontent.com/35630677/87757357-150daf00-c83d-11ea-9469-ede5956465bc.jpg)

**Comment by andywang425** [comment]
我觉得【礼物到期时间】这个功能意义肯定是有的，就算对某些用户来说没用也不碍事。  
【自动投币】bug：最大的问题就在于我两个号硬币都很多，我是真舍不得把币全投了来测这个bug，所以没法测试改得对不对。
谢谢你给出的日志，我觉得可以从错误码为-104入手，这样投错一次后可以及时终止投币。

**Comment by 15726238368** [comment]
> 我觉得【礼物到期时间】这个功能意义肯定是有的，就算对某些用户来说没用也不碍事。
> 【自动投币】bug：最大的问题就在于我两个号硬币都很多，我是真舍不得把币全投了来测这个bug，所以没法测试改得对不对。
> 谢谢你给出的日志，我觉得可以从错误码为-104入手，这样投错一次后可以及时终止投币。

我的重点不是在【礼物到期时间】有没有意义，可能我说的太多了重点不突出。
我是希望将“剩余礼物:指送完了所有粉丝牌，但仍有剩余的将在**1天内**过期的礼物。”这个“1天”也改为由【礼物到期时间】指定。也就是用户可以自由定义剩余礼物是几天内的礼物。
这个只是我个人需要用到这个功能，如果你不认为这个需求具有普遍性，那不改也无妨。

**Comment by andywang425** [comment]
> > 我觉得【礼物到期时间】这个功能意义肯定是有的，就算对某些用户来说没用也不碍事。
> > 【自动投币】bug：最大的问题就在于我两个号硬币都很多，我是真舍不得把币全投了来测这个bug，所以没法测试改得对不对。
> > 谢谢你给出的日志，我觉得可以从错误码为-104入手，这样投错一次后可以及时终止投币。
> 
> 我的重点不是在【礼物到期时间】有没有意义，可能我说的太多了重点不突出。
> 我是希望将“剩余礼物:指送完了所有粉丝牌，但仍有剩余的将在**1天内**过期的礼物。”这个“1天”也改为由【礼物到期时间】指定。也就是用户可以自由定义剩余礼物是几天内的礼物。
> 这个只是我个人需要用到这个功能，如果你不认为这个需求具有普遍性，那不改也无妨。

好像确实没啥普遍性，不大想做。如果你想修改这个时间的话，在原格式代码中搜索`满足到期时间小于一天`，跳到如下部分：
```javascript
                            && //满足到期时间小于一天
                            v.expire_at > MY_API.Gift.time && (v.expire_at - MY_API.Gift.time < 86400
                                && MY_API.CONFIG.SPARE_GIFT_ROOM != '0' && MY_API.CONFIG.SPARE_GIFT_UID != '0'
                                && feed > 0)) {
```
修改86400（单位秒）这个常量即可。
