### ISSUE TITLE
小bug【脚本窗口】显示位置

### ISSUE THREAD

**Issue by 15726238368** [andywang425/Bilibili-SGTH#8]
建议提高【脚本窗口】挂载的层次，让其显示在礼物/包裹的上层。
首先，“脚本窗口可以上下滚动！部分设置可能需要滚动后才能看到。”这个本身就有一点麻烦。
其次，当浏览器窗口全屏的情况下进入直播间页面加载脚本后，再缩小浏览器窗口，直播间画面也会跟着缩小，但【脚本窗口】不会缩小，这样就会造成下方的礼物栏遮挡在【脚本窗口】之上(如图)的bug，被遮挡部分无法通过上下滚动显示出来。
![mianban](https://user-images.githubusercontent.com/35630677/87761203-a4b65c00-c843-11ea-8057-f877505a6d74.jpg)
对于一些不同熟悉计算机的用户，很可能会不知所措。

建议让【脚本窗口】显示在整个直播窗口的上层，并取消滚动直接以最大高度显示，让用户通过滚动整个页面来查看下方内容而不是在【脚本窗口】内滚动，更加符合使用习惯。同时在窗口也添加一个相同功能的更加显眼的【隐藏窗口】按钮，防止用户不知道怎么收起窗口（效果如图）：
![2](https://user-images.githubusercontent.com/35630677/87762365-9c5f2080-c845-11ea-8268-89e1eb1fc0ea.jpg)

**Comment by andywang425** [comment]
1.【脚本窗口】显示方式变化：可以有，但没必要。能用上脚本的我相信这点计算机基础知识还是有的。
2. 【隐藏窗口】按钮：项目说明里写得明明白白，按钮在直播画面上方。如果还不会隐藏窗口那是用户自己的问题。
