### ISSUE TITLE
自动送礼失败

### ISSUE THREAD

**Issue by 15726238368** [andywang425/Bilibili-SGTH#9]
之前一直都正常，今天(7.18)14:00之后出现bug
包裹里有剩余一天的辣条，手动点击【立刻开始送礼】或到达【送礼时间】自动触发送礼时，都不能正常送出礼物。
![1](https://user-images.githubusercontent.com/35630677/87846710-70ef3b00-c904-11ea-9647-c263c43f7223.jpg)
![2](https://user-images.githubusercontent.com/35630677/87846714-76e51c00-c904-11ea-8041-8659aea4efa0.jpg)
怀疑B站相关接口修改，最近正在大规模更新直播相关功能
当然有可能是我本地的脚本出了问题，希望你也测试一下功能是否还能正常使用

**Comment by andywang425** [comment]
估计是b站api有变动，今晚应该能修复

**Comment by andywang425** [comment]
b站api又改回去了。。。

**Comment by X-Holmes** [comment]
问题重现，并且好像是只能自动送出辣条送不出小心心，包裹里有剩余1天的小心心但是不能自动送出去，会把所有送礼房间滚动一遍。
![1](https://user-images.githubusercontent.com/35630677/87846710-70ef3b00-c904-11ea-9647-c263c43f7223.jpg)

另外，【剩余礼物送直播间】功能中，好像只会送出辣条，1天的小心心没有算在剩余礼物中被送出。
以及再次请求将定义“剩余礼物”的剩余时间由默认1天改为自定义天数
